//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.517.0.

namespace BcfConverter.Model.Bcf21
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Header", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Header
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HeaderFile> _file;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("File", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<HeaderFile> File
        {
            get
            {
                return this._file;
            }
            private set
            {
                this._file = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Header" /> class.</para>
        /// </summary>
        public Header()
        {
            this._file = new System.Collections.ObjectModel.Collection<HeaderFile>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HeaderFile", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HeaderFile : IFileAttributes
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Filename", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Filename { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime Date { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Date property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Reference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reference { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 22.</para>
        /// <para xml:lang="en">Maximum length: 22.</para>
        /// <para xml:lang="en">Pattern: [0-9,A-Z,a-z,_$]*.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        [System.Xml.Serialization.XmlAttributeAttribute("IfcProject")]
        public string IfcProject { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 22.</para>
        /// <para xml:lang="en">Maximum length: 22.</para>
        /// <para xml:lang="en">Pattern: [0-9,A-Z,a-z,_$]*.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        [System.Xml.Serialization.XmlAttributeAttribute("IfcSpatialStructureElement")]
        public string IfcSpatialStructureElement { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _isExternal = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("isExternal")]
        public bool IsExternal
        {
            get
            {
                return this._isExternal;
            }
            set
            {
                this._isExternal = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    public partial interface IFileAttributes
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 22.</para>
        /// <para xml:lang="en">Maximum length: 22.</para>
        /// <para xml:lang="en">Pattern: [0-9,A-Z,a-z,_$]*.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        string IfcProject
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 22.</para>
        /// <para xml:lang="en">Maximum length: 22.</para>
        /// <para xml:lang="en">Pattern: [0-9,A-Z,a-z,_$]*.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        string IfcSpatialStructureElement
        {
            get;
            set;
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        bool IsExternal
        {
            get;
            set;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ViewPoint", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewPoint
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Viewpoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Viewpoint { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Snapshot", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Snapshot { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Index", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Index { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Index property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BimSnippet", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BimSnippet
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Reference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reference { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceSchema", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferenceSchema { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("SnippetType")]
        public string SnippetType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _isExternal = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("isExternal")]
        public bool IsExternal
        {
            get
            {
                return this._isExternal;
            }
            set
            {
                this._isExternal = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Topic", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Topic
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _referenceLink;
        
        [System.Xml.Serialization.XmlElementAttribute("ReferenceLink", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<string> ReferenceLink
        {
            get
            {
                return this._referenceLink;
            }
            private set
            {
                this._referenceLink = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ReferenceLink collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceLinkSpecified
        {
            get
            {
                return (this.ReferenceLink.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Topic" /> class.</para>
        /// </summary>
        public Topic()
        {
            this._referenceLink = new System.Collections.ObjectModel.Collection<string>();
            this._labels = new System.Collections.ObjectModel.Collection<string>();
            this._documentReference = new System.Collections.ObjectModel.Collection<TopicDocumentReference>();
            this._relatedTopic = new System.Collections.ObjectModel.Collection<TopicRelatedTopic>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Title { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Priority", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Priority { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Index", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Index { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Index property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _labels;
        
        [System.Xml.Serialization.XmlElementAttribute("Labels", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<string> Labels
        {
            get
            {
                return this._labels;
            }
            private set
            {
                this._labels = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Labels collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LabelsSpecified
        {
            get
            {
                return (this.Labels.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CreationDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime CreationDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CreationAuthor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreationAuthor { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ModifiedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime ModifiedDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ModifiedDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ModifiedAuthor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ModifiedAuthor { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DueDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime DueDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DueDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DueDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AssignedTo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssignedTo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Stage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Stage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BimSnippet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BimSnippet BimSnippet { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TopicDocumentReference> _documentReference;
        
        [System.Xml.Serialization.XmlElementAttribute("DocumentReference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<TopicDocumentReference> DocumentReference
        {
            get
            {
                return this._documentReference;
            }
            private set
            {
                this._documentReference = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DocumentReference collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentReferenceSpecified
        {
            get
            {
                return (this.DocumentReference.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TopicRelatedTopic> _relatedTopic;
        
        [System.Xml.Serialization.XmlElementAttribute("RelatedTopic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<TopicRelatedTopic> RelatedTopic
        {
            get
            {
                return this._relatedTopic;
            }
            private set
            {
                this._relatedTopic = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the RelatedTopic collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelatedTopicSpecified
        {
            get
            {
                return (this.RelatedTopic.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("TopicType")]
        public string TopicType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("TopicStatus")]
        public string TopicStatus { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TopicDocumentReference", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TopicDocumentReference : IDocumentReference
    {
        
        [System.Xml.Serialization.XmlElementAttribute("ReferencedDocument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferencedDocument { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _isExternal = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("isExternal")]
        public bool IsExternal
        {
            get
            {
                return this._isExternal;
            }
            set
            {
                this._isExternal = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    public partial interface IDocumentReference
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        string Guid
        {
            get;
            set;
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        bool IsExternal
        {
            get;
            set;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TopicRelatedTopic", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TopicRelatedTopic
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Comment", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Comment
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime Date { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Author", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Author { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Comment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CommentProperty { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Viewpoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CommentViewpoint Viewpoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ModifiedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime ModifiedDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ModifiedDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ModifiedAuthor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ModifiedAuthor { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CommentViewpoint", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CommentViewpoint
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.517.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Markup", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Markup", Namespace="")]
    public partial class Markup
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HeaderFile> _header;
        
        [System.Xml.Serialization.XmlArrayAttribute("Header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("File", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<HeaderFile> Header
        {
            get
            {
                return this._header;
            }
            private set
            {
                this._header = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Header collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeaderSpecified
        {
            get
            {
                return (this.Header.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Markup" /> class.</para>
        /// </summary>
        public Markup()
        {
            this._header = new System.Collections.ObjectModel.Collection<HeaderFile>();
            this._comment = new System.Collections.ObjectModel.Collection<Comment>();
            this._viewpoints = new System.Collections.ObjectModel.Collection<ViewPoint>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Topic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Topic Topic { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Comment> _comment;
        
        [System.Xml.Serialization.XmlElementAttribute("Comment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Comment> Comment
        {
            get
            {
                return this._comment;
            }
            private set
            {
                this._comment = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Comment collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommentSpecified
        {
            get
            {
                return (this.Comment.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ViewPoint> _viewpoints;
        
        [System.Xml.Serialization.XmlElementAttribute("Viewpoints", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ViewPoint> Viewpoints
        {
            get
            {
                return this._viewpoints;
            }
            private set
            {
                this._viewpoints = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Viewpoints collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ViewpointsSpecified
        {
            get
            {
                return (this.Viewpoints.Count != 0);
            }
        }
    }
}
