//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace bcf.bcf30 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class VisualizationInfo {
        
        private Components componentsField;
        
        private object itemField;
        
        private Line[] linesField;
        
        private ClippingPlane[] clippingPlanesField;
        
        private Bitmap[] bitmapsField;
        
        private string guidField;
        
        /// <remarks/>
        public Components Components {
            get {
                return this.componentsField;
            }
            set {
                this.componentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrthogonalCamera", typeof(OrthogonalCamera))]
        [System.Xml.Serialization.XmlElementAttribute("PerspectiveCamera", typeof(PerspectiveCamera))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Line[] Lines {
            get {
                return this.linesField;
            }
            set {
                this.linesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ClippingPlane[] ClippingPlanes {
            get {
                return this.clippingPlanesField;
            }
            set {
                this.clippingPlanesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Bitmap[] Bitmaps {
            get {
                return this.bitmapsField;
            }
            set {
                this.bitmapsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Components {
        
        private Component[] selectionField;
        
        private ComponentVisibility visibilityField;
        
        private ComponentColoringColor[] coloringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Component[] Selection {
            get {
                return this.selectionField;
            }
            set {
                this.selectionField = value;
            }
        }
        
        /// <remarks/>
        public ComponentVisibility Visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Color", IsNullable=false)]
        public ComponentColoringColor[] Coloring {
            get {
                return this.coloringField;
            }
            set {
                this.coloringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Component {
        
        private string originatingSystemField;
        
        private string authoringToolIdField;
        
        private string ifcGuidField;
        
        /// <remarks/>
        public string OriginatingSystem {
            get {
                return this.originatingSystemField;
            }
            set {
                this.originatingSystemField = value;
            }
        }
        
        /// <remarks/>
        public string AuthoringToolId {
            get {
                return this.authoringToolIdField;
            }
            set {
                this.authoringToolIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string IfcGuid {
            get {
                return this.ifcGuidField;
            }
            set {
                this.ifcGuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Bitmap {
        
        private BitmapFormat formatField;
        
        private string referenceField;
        
        private Point locationField;
        
        private Direction normalField;
        
        private Direction upField;
        
        private double heightField;
        
        /// <remarks/>
        public BitmapFormat Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public Point Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public Direction Normal {
            get {
                return this.normalField;
            }
            set {
                this.normalField = value;
            }
        }
        
        /// <remarks/>
        public Direction Up {
            get {
                return this.upField;
            }
            set {
                this.upField = value;
            }
        }
        
        /// <remarks/>
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum BitmapFormat {
        
        /// <remarks/>
        png,
        
        /// <remarks/>
        jpg,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Point {
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        /// <remarks/>
        public double X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public double Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Direction {
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        /// <remarks/>
        public double X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public double Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClippingPlane {
        
        private Point locationField;
        
        private Direction directionField;
        
        /// <remarks/>
        public Point Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public Direction Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Line {
        
        private Point startPointField;
        
        private Point endPointField;
        
        /// <remarks/>
        public Point StartPoint {
            get {
                return this.startPointField;
            }
            set {
                this.startPointField = value;
            }
        }
        
        /// <remarks/>
        public Point EndPoint {
            get {
                return this.endPointField;
            }
            set {
                this.endPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerspectiveCamera {
        
        private Point cameraViewPointField;
        
        private Direction cameraDirectionField;
        
        private Direction cameraUpVectorField;
        
        private double fieldOfViewField;
        
        private double aspectRatioField;
        
        /// <remarks/>
        public Point CameraViewPoint {
            get {
                return this.cameraViewPointField;
            }
            set {
                this.cameraViewPointField = value;
            }
        }
        
        /// <remarks/>
        public Direction CameraDirection {
            get {
                return this.cameraDirectionField;
            }
            set {
                this.cameraDirectionField = value;
            }
        }
        
        /// <remarks/>
        public Direction CameraUpVector {
            get {
                return this.cameraUpVectorField;
            }
            set {
                this.cameraUpVectorField = value;
            }
        }
        
        /// <remarks/>
        public double FieldOfView {
            get {
                return this.fieldOfViewField;
            }
            set {
                this.fieldOfViewField = value;
            }
        }
        
        /// <remarks/>
        public double AspectRatio {
            get {
                return this.aspectRatioField;
            }
            set {
                this.aspectRatioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrthogonalCamera {
        
        private Point cameraViewPointField;
        
        private Direction cameraDirectionField;
        
        private Direction cameraUpVectorField;
        
        private double viewToWorldScaleField;
        
        private double aspectRatioField;
        
        /// <remarks/>
        public Point CameraViewPoint {
            get {
                return this.cameraViewPointField;
            }
            set {
                this.cameraViewPointField = value;
            }
        }
        
        /// <remarks/>
        public Direction CameraDirection {
            get {
                return this.cameraDirectionField;
            }
            set {
                this.cameraDirectionField = value;
            }
        }
        
        /// <remarks/>
        public Direction CameraUpVector {
            get {
                return this.cameraUpVectorField;
            }
            set {
                this.cameraUpVectorField = value;
            }
        }
        
        /// <remarks/>
        public double ViewToWorldScale {
            get {
                return this.viewToWorldScaleField;
            }
            set {
                this.viewToWorldScaleField = value;
            }
        }
        
        /// <remarks/>
        public double AspectRatio {
            get {
                return this.aspectRatioField;
            }
            set {
                this.aspectRatioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewSetupHints {
        
        private bool spacesVisibleField;
        
        private bool spaceBoundariesVisibleField;
        
        private bool openingsVisibleField;
        
        public ViewSetupHints() {
            this.spacesVisibleField = false;
            this.spaceBoundariesVisibleField = false;
            this.openingsVisibleField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SpacesVisible {
            get {
                return this.spacesVisibleField;
            }
            set {
                this.spacesVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SpaceBoundariesVisible {
            get {
                return this.spaceBoundariesVisibleField;
            }
            set {
                this.spaceBoundariesVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OpeningsVisible {
            get {
                return this.openingsVisibleField;
            }
            set {
                this.openingsVisibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentVisibility {
        
        private ViewSetupHints viewSetupHintsField;
        
        private Component[] exceptionsField;
        
        private bool defaultVisibilityField;
        
        public ComponentVisibility() {
            this.defaultVisibilityField = false;
        }
        
        /// <remarks/>
        public ViewSetupHints ViewSetupHints {
            get {
                return this.viewSetupHintsField;
            }
            set {
                this.viewSetupHintsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Component[] Exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultVisibility {
            get {
                return this.defaultVisibilityField;
            }
            set {
                this.defaultVisibilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ComponentColoringColor {
        
        private Component[] componentsField;
        
        private string colorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Component[] Components {
            get {
                return this.componentsField;
            }
            set {
                this.componentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
}
