//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1144.0 using the following command:
// xscgen -n BcfToolkit.Model.Bcf21 --nullable --output ./Model/Bcf21 ./Resources/Schemas/Bcf21/version.xsd
namespace BcfToolkit.Model.Bcf21
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1144.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Version", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Version", Namespace="")]
    public partial class Version
    {
        
        [System.Xml.Serialization.XmlElementAttribute("DetailedVersion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DetailedVersion { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("VersionId")]
        public string VersionId { get; set; }
    }
}
