# This is a basic workflow to help you get started with Actions

name: Bcf converter CI/CD

# Controls when the action will run.
on: [push, pull_request]
jobs:
  test:
    name: "Running tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: "Install dotnet format"
        run: dotnet tool update --global dotnet-format

      - name: "Run dotnet format"
        working-directory: ./src
        run: dotnet format --verbosity diagnostic --verify-no-changes

      - name: "Unit tests"
        working-directory: ./src
        run: dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=./artifacts/test-output.xml"

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./artifacts/*.xml
