# This is a basic workflow to help you get started with Actions

name: bcf-toolkit CI/CD

# Controls when the action will run.
on: [push, pull_request]
jobs:
  test:
    name: "Running tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet format
        run: dotnet tool update --global dotnet-format

      - name: Run dotnet format
        run: dotnet format --verbosity diagnostic --verify-no-changes

      - name: Unit tests
        run: dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=./artifacts/test-output.xml"

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./artifacts/*.xml

      - name: Create Nuget package
        working-directory: ./src/bcf-toolkit
        if: github.ref_type == 'tag'
        run: dotnet pack -p:PackageVersion=${{ github.ref_name }} --configuration Release bcf-toolkit.csproj --output ../../dist
      
      - name: Publish package to Nuget
        if: github.ref_type == 'tag'
        run: dotnet nuget push dist/*.nupkg --source https://api.nuget.org/v3/index.json --no-symbols --api-key ${{ secrets.SMINO_NUGET_API_KEY }} --skip-duplicate
